### ISSUE TITLE
[Bug] su reporting "unrecognized option"

### ISSUE THREAD

**Issue by ildar** [NeoApplications/Neo-Backup#562]
**Description**
First command launch through `su` fails. Su complains "unrecognized option"

**Steps To Reproduce**
Just try to backup anything.

**System Information(please complete the following information):**

- Device: Doogee S59 pro
- Android Version: 12
- ROM: AOSP 12 by Phh, FOSS flavor
- App's Version: Version 8.0.2 (8016), F-Droid

Log:

**Comment by ildar** [comment]
{"logDate":"2022-05-23T07:50:12.046","deviceName":"phhgsi_arm64_ab","sdkCodename":"12","cpuArch":"arm64-v8a","logText":"a: q7.d.c occurred on data backup: q7.d$c: /system/bin/phh-su: unrecognized option `--mount-master'\nUsage: su [options] [--] [-] [LOGIN] [--] [args...]\nOptions:\n  --daemon                      start the su daemon agent\n  -c, --command COMMAND         pass COMMAND to the invoked shell\n  --context context             Change SELinux context\n  -h, --help                    display this help message and exit\n  -, -l, --login                pretend the shell to be a login shell\n  -m, -p,\n  --preserve-environment        do not change environment variables\n  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh\n  -u                            display the multiuser mode and exit\n  -v, --version                 display version number and exit\n  -V                            display version code and exit,\n                                this is used almost exclusively by Superuser.apk"}

**Comment by machiav3lli** [comment]
Phh's su implementation doesn't support some of the functions that we use. This has been already reported to him but some common users. As it stands now only Magisk does support those. If we'll need to implement an alternative to avoid this command or if it'll get fixed on phh's side is still not clear, but the second one is the preferred solution

**Comment by dp0s** [comment]
I had the same error when using the su package for lineage os 16. After reading this thread, I fixed it by flashing magisk instead. :) backups are working now.

**Comment by hg42** [comment]
please test the current pumpkin test apk

https://t.me/neo_backup/36949

or tell me per e-mail, if you don't use Telegram, then I answer with the apk

**Comment by ildar** [comment]
IMHO it's best to support the widest range of ROMs so I suggest having the
FR for it.

Next, you write Phh's SU is incomplete. Do you have the issue #?

**Comment by hg42** [comment]
no one defines what is a complete su...

facts:

SuperUser has --mount-master
Magisk has --mount-master
PHH does not

--mount-master is necessary to access all the files, in case mount namespaces are used to isolate 

so at least it's incomplete in this situation. It could be discussed if this is a responsibility of su, but usually su is used to access things we can't access otherwise, so yeah for me it's su's job

I think there are situations, where we have mount namespace isolation and need that option

and there are other situations where we don't have such isolation (that's why good old oandbackup works for those, but then it doesn't work for others).

we don't want to add native code, so using setns is not an option

PHH is a small number of systems

conclusion:

if PHH is used when namespace isolation isn't present, then my workaround shoukd work
= don't use the option if su chokes on it

if PHH is used in the isolated case, we cannot access the files, but there is no other solution then, the user shoukd install a root solution that solves that

**Comment by ildar** [comment]
Thank you for the detailed explanation. I think @phhusson wants to know that
Anyway I'll try your APK, I dunno how I missed it.

**Comment by hg42** [comment]
the workaround was commited in June 1, so it shoukd be present in releases starting with 8.0.3 I think.

**Comment by phhusson** [comment]
Thanks @ildar for the ping.


> --mount-master is necessary to access all the files, in case mount namespaces are used to isolate

Looking at https://twitter.com/topjohnwu/status/1279508461370269696?lang=en, this looks wrong. With my SU, you don't start in process' mount namespace, you start in a root namespace. I don't think it's the master namespace (though it might be I'm not sure), but master namespace would be useful only if you need to mount new partitions/fuse/stuff. I really can't see how you would need this.

It could be considered a bug of my SU to not start in process' mount namespace (though honestly, except for accessing litterally "/sdcard/" rather than "/data/media/0/", I don't see the point of using process' mount namespace), but since you need the opposite, that should be fine

So uh, can you please explain why you need this parameter?

**Comment by ildar** [comment]
FTR, I tried and stumbled at
https://github.com/NeoApplications/Neo-Backup/issues/657

**Comment by phhusson** [comment]
@ildar This error is typical of apps not using the standard Android way of calling `su`, which is `su <uid> <command>`, but instead just do `su command`
so like `su 0 ls` instead of `su ls`

**Comment by hg42** [comment]
thanks @phhusson 

I am not part of the project from the beginning.

I guess the reasoning was like that:

we need access to all kinds of files, anything in the system (for special backups), and files from all apps, and our own.
So a global namespace looks like what we need.

Actually, we added the option, when users started to get errors.

Android is playing an isolation game and I expect it to get even worse.

Though, I wasn't aware that `su <uid> xxx` is different from a simple `su`.
Neither did I find this as a possible solution to such problems.
Thanks for mentioning it.

If I understand this correctly, we can remove the --mount-master option then?
And it will work with all su variants?

Perhaps you could document this somewhere, may be as an FAQ, something like:
"why --mount-master isn't necessary",
because when searching for solutions, I couldn't find it?

**Comment by phhusson** [comment]
Quick answer: no su 0 won't be equivalent to --master-mount
I'm just saying that based on what magisk author said, this option shouldn't be needed on my gsi.
But I'll ping him for clarifications.

13 oct. 2022 17:11:18 Harald ***@***.***>:

**Comment by hg42** [comment]
well, I think I am on the right track now...

I always thought su on Android is not very different from su on Linux.
using libsu seems also to be critical...
I'm investigating it right now.

Actually, I always wondered why NB doesn't work on an emulator image.
This seems to be related. I can execute toybox manually but the libsu function fails. It seems to invoke it in a different way.
I'll first try to use my own function, we already need it, because the convenient functions of libsu don't stream...

**Comment by hg42** [comment]
`su` in emulator is a different story...

**Comment by hg42** [comment]
some more facts:

```
Magisk isolated
    NB without —mount-master but uid=0
        -> /data/user/0/pkg invisible
    NB with —mount-master
        -> works
Magisk inherited
    NB without —mount-master but uid=0
        -> /data/user/0/pkg invisible
    NB with —mount-master
        -> works
Magisk global
    NB without —mount-master but uid=0
        -> works
    NB with —mount-master
        -> works
```

so `su 0` isn't a general solution, in fact it doesn't matter when Magisk root is installed.

I understand that PHH uses another namespace:
You said:

> With my SU, you don't start in process' mount namespace, you start in a root namespace

is this comparable with Magisk's global namespace option?

**Comment by hg42** [comment]
can someone please provide the output of phh `su --help`?
(I hope it has --help)

I'm asking, because I found that the su used in an Google emulator image doesn't have -c.
The --help output may also help to identify the su variant.

At least Magisk su outputs `MagiskSU` as the first line, which is quite nice.

Magisk su doesn't execute the command without -c, instead it starts a root shell, so -c is necessary.
For app development, it's a good thing, if we could establish some standards.
Otherwise, the number of combinations of all the dependencies explodes.

**Comment by hg42** [comment]
is there a phh root solution that I could install on x86 or x86_64 (on emulator)?
or a suitable GSI image that I could use?

I guess a GSI image needs some support from the device?
or would it be possible to run it via a standard qemu-*arm* or similar?

**Comment by hg42** [comment]
> @ildar you are now on Magisk, do you want to go back and try if it solves the problem?
> I would provide a test apk first

I confused it with the other thread, do you still use phh?

**Comment by hg42** [comment]
@ildar please try this:

https://t.me/neo_backup/41974

**Comment by ildar** [comment]
Hello,
I'm still at Phh's ROM with Phh's SU.
It failed with your debug apk, saying:
> Cannot execute -c: No such file

Then what you asked:
```
phhgsi_arm64_ab:/ $ su --help
Usage: su [options] [--] [-] [LOGIN] [--] [args...]

Options:
  --daemon                      start the su daemon agent
  -c, --command COMMAND         pass COMMAND to the invoked shell
  --context context             Change SELinux context
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default
/system/bin/sh
  -u                            display the multiuser mode and exit
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by
Superuser.apk
```
Thanks a lot.

**Comment by ildar** [comment]
> is there a phh root solution that I could install on x86 or x86_64 (on
emulator)?

This one is ancient, so I'm not sure it can work on the modern Android
version emu.
But it worked just fine at least with Android 7.
https://filebin.net/ofhpq2asrd9j02lx

The app is: https://f-droid.org/en/packages/me.phh.superuser

**Comment by ildar** [comment]
> or a suitable GSI image that I could use?

ah! sure!
https://github.com/phhusson/treble_experimentations/wiki/Frequently-Asked-Questions-%28FAQ%29

**Comment by phhusson** [comment]
For `setns` call, `nsenter` is pre-installed on Android (looking at git logs, since at least 2015) which can do setns. So i guess `su 0 nsenter -t 1 -m ls /data/user/0` is equivalent on magisk to `--mount-master`.

But I confirm that when doing `su 0 ls /data/user/0` on my SU, all pkgs are listed, not just your own.

**Comment by phhusson** [comment]
I discussed with magisk's author who confirmed my understanding.
I'll try upgrading my su to ignore `--mount-master` altogether, though considering it's shipped inside ROMs without any OTA mechanism, i'll probably take a lot of time to trickle down

**Comment by hg42** [comment]
oh that's interesting:

it complains about -c

> Cannot execute -c: No such file

but it shoukdn't?

> -c, --command COMMAND pass COMMAND to the invoked shell

**Comment by hg42** [comment]
> https://filebin.net/ofhpq2asrd9j02lx

oh I didn't see that x86 is included in those zips

**Comment by hg42** [comment]
> I'll try upgrading my su to ignore `--mount-master` altogether, though considering it's shipped inside ROMs without any OTA mechanism, i'll probably take a lot of time to trickle down

I guess ignoring it will not help alone, because the uid isn't used in that case (--mount-master makes it irrelevant as far as I understand).
May be you could act like uid=0 was given...

**Comment by phhusson** [comment]
> oh that's interesting:
> 
> it complains about -c
> 
> > Cannot execute -c: No such file

Can you tell the exact command line you're sending?

**Comment by hg42** [comment]
there are subtle differences how the command line options work, despite they look very similar:

```
MagiskSU

Usage: su [options] [-] [user [argument...]]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        preserve the entire environment
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -v, --version                 display version number and exit
  -V                            display version code and exit
  -mm, -M,
  --mount-master                force run in the global mount namespace
```

phh su (I got this from the sources which I had not found before, because I thought SuperUser would only be the app):
```
Usage: su [options] [--] [-] [LOGIN] [--] [args...]
Options:
  --daemon                      start the su daemon agent
  -c, --command COMMAND         pass COMMAND to the invoked shell
  --context context             Change SELinux context
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default " DEFAULT_SHELL "
  -u                            display the multiuser mode and exit
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by Superuser.apk
```

Magisk su
* needs `-c`  otherwise it starts a shell without a command.
  That means `su 0 ls /dev` only changes to root.

* parsing arguments is weird:
  `su -c "ls /dev" /etc` will be the same like `ls /dev /etc`
  `su -c "ls /dev" 0` will complain `ls: 0: No such file or directory`

* doesn't have `--`

phh su (what I see in the sources, not tested, please confirm or complain):

* needs options first, so a `su 0 -c "ls /dev /etc"`, which would be compatible isn't possible

* there is no identification string in `--help` or `--version` or `-V`

As far as I see, this means, that we need to identify which su we have and construct the command line individually.

**Comment by phhusson** [comment]
Well, I'm fine with fixing my SU to be compatible with magik's syntax, I just need to know which one you use, hence I'm asking for the exact format you're using. If I understand correctly, it's:

`su --mount-master -c 'ls /dev'` ?

Right? I'll also add a marker in -V

**Comment by hg42** [comment]
> Can you tell the exact command line you're sending?

it is built like this (Kotlin code, in that workaround he tried):

```
"su $suOptions -c sh ${quote(tarScript)} create $utilBoxQ $options ${
                quote(sourcePath)
            }"
```

where:

```
val suMountOptions get() =
    if (pref_useMountMaster.value && ShellHandler.isMountMaster)
        "--mount-master"
    else if (pref_useSu0.value)
        "0"
    else
        ""
```

`$tarScript` is the path of a shell script, that gets some parameters.

both preferences `pref_*` are set, and isMountMaster isn't set.

So it should be something like:

`su 0 -c /some/path/tar.sh create /system/bin/toybox /some/data/directory`

It should be:

`-c '/some/path/tar.sh create /system/bin/toybox /some/data/directory'`

for phh su

In the phh `su.c` code I see, that options are processed first, so the `0` will stop option processing (I think), then `-c` is taken as the command and the rest as arguments to whatever (not for the command, I think, it's probably for the shell that may be started if a command isn't present)

**Comment by hg42** [comment]
> `su --mount-master -c 'ls /dev'` ?

yes, usually we omit the quotes, but I think we shouldn't (from what I saw in Magisk su.c).

If the uid parameter must be set, it would need to go in front of the `-c`, because everything after the `-c` is part of the command in Magisk.
All following arguments are concatenated together (which is also kind of weird, when thinking about quoting, the shell removes the quotes... I think this has some additional pitfalls).

I see, the code in [MagiskSU su.c](
https://github.com/topjohnwu/MagiskSU/blob/master/su.c)
looks just like your's.
It seems it cannot handle the 0 in front of the options, either.

Which means, it cannot execute `su 0 command`, because it needs a `-c` to execute a command at all (otherwise it invokes the shell).
And it cannot do `su 0 -c command` either, because option processing ends with the uid `0`.

> I'll also add a marker in -V

actually, Magisk does:

```
% adb shell su -V     
25200
```

and puts the marker in `--help` (this could be used to detect su type and available options in one go):

```
% adb shell su --help
MagiskSU

Usage: su [options] [-] [user [argument...]]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        preserve the entire environment
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -v, --version                 display version number and exit
  -V                            display version code and exit
  -mm, -M,
  --mount-master                force run in the global mount namespace
```

As far as I understand, you need to interpret `--mount-master` as `uid=0` to work, right?
At least that's what you suggested instead.

**Comment by hg42** [comment]
hmm, the code in the link above suggests that the indentification line would also contain the version and version code:

```
static void usage(int status) {
	FILE *stream = (status == EXIT_SUCCESS) ? stdout : stderr;

	fprintf(stream,
	"MagiskSU v" xstr(MAGISK_VERSION) "(" xstr(MAGISK_VER_CODE) ")\n\n"
```

oh, yeah, the repo is some years old...where is the current source?

LOL, it also says:

> **About**
> Keeping phh's Superuser fresh

**Comment by hg42** [comment]
@phhusson

what would be the correct way to invoke a command with uid=0 ?

let's say the Magisk command is:

`su --mount-master -c ls /data/data/`

we already tried:

`su -c ls /data/data`

which doesn't work.

`su 0 -c ls /data/data`

which complains `Cannot execute -c: No such file`

I know phh only uses the next argument for `-c`, so the first alternative would do an ls.

I would probably use:

`su -c "ls /data/data" 0`

**Comment by ildar** [comment]
True. Also `su -c "ls /data/data"` works
```
phhgsi_arm64_ab:/ $ su --mount-master -c ls /data/data/

/system/bin/phh-su: unrecognized option `--mount-master'
...
phhgsi_arm64_ab:/ $ su -c ls /data/data
Unknown id: /data/data
phhgsi_arm64_ab:/ $ su 0 -c ls /data/data
Cannot execute -c: No such file or directory
phhgsi_arm64_ab:/ $ su -c "ls /data/data" 0
android
android.auto_generated_rro_product__
android.auto_generated_rro_vendor__
android.ext.services
...
phhgsi_arm64_ab:/ $ su -c "ls /data/data"
android
android.auto_generated_rro_product__
...
```

**Comment by hg42** [comment]
ah, nice, so it's not an access problem, but a simple command line syntax issue.

What about these?:
```
su 0 ls /data/data
su 0 -- ls /data/data
```

**Comment by ildar** [comment]
Yes, sorry for the delay.

> su 0 ls /data/data
> su 0 -- ls /data/data

Both work.

**Comment by hg42** [comment]
I have a solution to support more su implementations.

They only need to support the simple command line `su 0` (or `su --mount-master 0` if it exists) and this command must give access to directories like `/data/user/0/` etc. (so no mount isolation takes place or similar technics or they are overridden by the root method in some way).

The command is now piped into `su 0` on stdin.
This is something, I wanted to do when I started contributing, because it is the only way to circumvent command line differences and quoting/escaping problems etc. for different su implementations on Android. I considered this in a more general context, similar to how Magisk libsu works. It creates a single shell that runs continuously and pipes the commands to it and receives the outputs.

For the tar command I thought it would be a bad idea, because we need to pipe the tar archive to tar's stdin. And it must be closed afterwards, to finish the tar command.
But it's a no-brainer, if the shell is only created for a single command and data streamed after it (and no more commands follow).

In an upcoming pumpkin version, I will start a test phase.

**Comment by hg42** [comment]
please test this:

https://t.me/neo_backup/42531

I think it will work with phh su now.

be careful, only use on test data, read the message (and the disclaimer)

**Comment by ildar** [comment]
This one works great, thanks a lot!!!

**Comment by hg42** [comment]
the new one?

**Comment by ildar** [comment]
the latest,
> https://t.me/neo_backup/42531

**Comment by hg42** [comment]
LOL I just added a new one.

new version for testing:
https://t.me/neo_backup/42590

the other one had some problems.

Though some of my problems came from using toybox-ext Magisk module.
The ls -l command outputs numeric uid gid, but it should output the names.

Also, if the tar command encountered a socket it choked. This is solved.

**Comment by ildar** [comment]
REGRESSION: the problem is back in 8.3.0.
1. see screenshot below
2. no new log in LOGS folder
3. the button "Save" on the screenshot doesn't do anything.

**Comment by hg42** [comment]
hmm, that's interesting.

So we have two problems:

* your `su` doesn't understand `--mount-master`, but `libsu` thinks it is mount master, so we use `--mount-master`
* another one has an `su` with `--mount-master`, but `libsu` doesn't think so, so we don't use it

Looks like it would be inverted. But it works for most. It seems only to be a problem in a few situations.

We didn't change that code. The change seems to be the libsu version, that was updated from 3.x to 5.x.
I guess the detection or the meaning of the flag changed.
Maybe `libsu` detects, that it **is** mount master, and not that `--mount-master` is available as an option.

Well, because of the other guy, I already changed the detection, so it doesn't follow what `libsu` thinks any more,
instead we directly test, if `su` understands `--mount-master`.

please test https://t.me/neo_backup/47288

**Comment by ildar** [comment]
Works with Phh SU

**Comment by hg42** [comment]
> Works with Phh SU

thanks for the confirmation

**Comment by hg42** [comment]
@ildar 

can you test this apk with a new way to handle mount namespaces?:

https://t.me/neo_backup/47438

it doesn't need mount namespace support from su

**Comment by ildar** [comment]
It works 👍

**Comment by hg42** [comment]
thanks
